apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      nodePort: 30090
      name: console
    - port: 9000
      name: s3
  type: NodePort
