apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: minio
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            periodSeconds: 20
          volumeMounts:
            - mountPath: /data
              name: data
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_ROOT_PASSWORD
              value: password
          lifecycle:
            # Create a bucket called mybucket
            postStart:
              exec:
                command:
                -  "/bin/sh"
                - "-c"
                - |
                  while ! mc mb /data/mybucket; do echo 'Wait minio to startup...' && sleep 0.5; done;