# A ClusterRole with the necessary privileges for Workflows pods.
# Defined as a ClusterRole so it can be reused in different namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: executor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch

---
# Gives the 'default' ServiceAccount in the 'default' Namespace privileges for workflows
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-executor
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: executor
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
