apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories  # well-known ConfigMap name workflows will look for
  annotations:
    # Specifies the default repository to use (defined in the data key)
    workflows.argoproj.io/default-artifact-repository: mybucket
data:
  mybucket: |
    archiveLogs: false
    s3:
      bucket: mybucket
      endpoint: minio.minio.svc:9000
      insecure: true
      accessKeySecret:
        name: mybucket
        key: username
      secretKeySecret:
        name: mybucket
        key: password
      keyFormat: "wf-artifacts/{{workflow.name}}/{{pod.name}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: mybucket
type: Opaque
stringData:
  username: admin
  password: password
