apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: containerset-dag-
spec:
  entrypoint: containerset
  templates:
    - name: containerset
      containerSet:
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        containers:
          - name: a
            image: alpine:latest
            command: ["sh", "-c", "echo A | tee -a /workspace/out"]
          - name: b
            dependencies: [a]
            image: alpine:latest
            command: ["sh", "-c", "echo B | tee -a /workspace/out"]
          - name: c
            dependencies: [a]
            image: alpine:latest
            command: ["sh", "-c", "echo C | tee -a /workspace/out"]
          - name: d
            dependencies: [b, c]
            image: alpine:latest
            command: ["sh", "-c", "echo D | tee -a /workspace/out"]
          - name: main
            dependencies: [d]
            image: alpine:latest
            command: ["cat", "/workspace/out"]
      volumes:
        - name: workspace
          emptyDir: {}
