apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: plugin-template-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: hello-plugin
            template: hello-plugin
        - - name: print-result
            template: print-result
            arguments:
              parameters:
                - name: result
                  value: "{{steps.hello-plugin.outputs.parameters.foo}}"

    - name: hello-plugin
      plugin:
        hello: {}
      outputs:
        parameters:
          - name: foo
            value: ""

    - name: print-result
      inputs:
        parameters:
          - name: result
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.result}}"]
