apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-mutex-
spec:
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: sleep
        template: sleep
      - name: whalesay
        template: whalesay

  - name: sleep
    synchronization:
      mutex:
        name: template-mutex
    container:
      image: busybox:latest
      command: [sh, -c]
      args: ["sleep 1m"]

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
