apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-semaphore-
spec:
  entrypoint: sleep
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-semaphores
        key: workflow
  templates:
  - name: sleep
    container:
      image: busybox:latest
      command: [sh, -c]
      args: ["sleep 1m"]
